services:
  app-springboot:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:9090"
    environment:
      # Connexion à XAMPP
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/suivi_prj_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    extra_hosts:
      - "host.docker.internal:host-gateway"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" # On accèdera à Prometheus via localhost:9091

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
