# Nom de l'application
spring.application.name=suivi-projets

# Configuration de la Base de Données
spring.datasource.url=jdbc:mysql://localhost:3306/suivi_prj_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port du serveur (Backend)
server.port=9090

# --- CONFIGURATION MONITORING (ACTUATOR & PROMETHEUS) ---
# Exposer les points d'accès pour Prometheus et la santé du système
management.endpoints.web.exposure.include=prometheus,health,info

# Activer spécifiquement le format Prometheus
management.endpoint.prometheus.enabled=true

# Optionnel : Ajouter des tags pour identifier l'application dans Grafana
management.metrics.tags.application=${spring.application.name}
